function main() {
  return [
    {
      id: 1,
      name: "Kanban",
      path: "/kanban/index",
      icon: "icon-activity",
      rank: 1,
      status: "enabled",
      visible_menu: 0,
      blocks: 0,
      parent: null,
    },
    {
      id: 3,
      name: "Customers",
      path: "/table/customer.trail",
      icon: "icon-users",
      rank: 3,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: null,
    },
    {
      id: 4,
      name: "Projects",
      path: "/table/project.top",
      icon: "icon-book",
      rank: 4,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: null,
    },
    {
      id: 5,
      name: "Tasks",
      path: "/table/task.my",
      icon: "icon-compass",
      rank: 5,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: null,
    },
    {
      id: 6,
      name: "Contracts",
      path: "/table/contract",
      icon: "icon-inbox",
      rank: 6,
      status: "enabled",
      visible_menu: 0,
      blocks: 0,
      parent: null,
    },
    {
      id: 7,
      name: "Channels",
      path: "/table/channel",
      icon: "icon-aperture",
      rank: 7,
      status: "enabled",
      visible_menu: 0,
      blocks: 0,
      parent: null,
    },
    {
      id: 8,
      name: "Trails",
      path: "/table/customer.trail",
      rank: 1,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 3,
    },
    {
      id: 9,
      name: "Customer List",
      path: "/table/customer.db",
      rank: 2,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 3,
    },
    {
      id: 10,
      name: "Follows",
      path: "/table/project.top",
      rank: 1,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 4,
    },
    {
      id: 11,
      name: "My Projects",
      path: "/table/project.my",
      rank: 2,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 4,
    },
    {
      id: 12,
      name: "Project List",
      path: "/table/project.db",
      rank: 2,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 4,
    },
    {
      id: 13,
      name: "My Tasks",
      path: "/table/task.my",
      rank: 1,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 5,
    },
    {
      id: 14,
      name: "Task List",
      path: "/table/task.db",
      rank: 2,
      status: "enabled",
      visible_menu: 1,
      blocks: 0,
      parent: 5,
    },
  ];
}
